### ISSUE TITLE
POM issues with duplicate dependency and odd test resources

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#107]
Anyone know why we have the same dependency artifact twice in the pom.xml?

```
 <dependency>
     <groupId>${project.groupId}</groupId>
     <artifactId>core</artifactId>
     <version>${gn.project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>schema-core</artifactId>
      <version>${project.version}</version>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>

```
Also anyone know why the plugin folder is marked as a test resource and why there is reference to a test resource folder that does not exists?

```
<testResources>
      <testResource>
        <directory>src/test/resources/org/fao/geonet</directory>
      </testResource>
      <testResource>
        <directory>src/main/plugin/iso19139.ca.HNAP</directory>
      </testResource>
    </testResources>
```

I noticed that these same issues exist in schema iso19139 - So may be they were copied over from there?

**Comment by jodygarnett** [comment]
Q: Anyone know why we have the same dependency artifact twice in the pom.xml?
A: Those are two different things:

* `core` references https://github.com/geonetwork/core-geonetwork/tree/master/core
* `schema-core` references https://github.com/geonetwork/core-geonetwork/tree/master/schemas/schema-core

`schema-core` publishes a couple different artifacts:

* `jar`used to help write schema plugins 
* `test-jar`often used for resources or base classes supporting the writing of test cases

**Comment by jodygarnett** [comment]
Q: Also anyone know why the plugin folder is marked as a test resource and why there is reference to a test resource folder that does not exists?
A: This is indeed hard to figure out and I am not sure I have it right

We need the plugin `iso19139.ca.HNAP` content available to run tests against it:

* It is packaged for other modules as a `zip`, ... web app for example can depend on the `zip` and include in `war`
* But before we package we would like to test the contents, `testResource` is how to do this ...

I believe `src/test/resources` is just the normal `testResource` contents included to aid in unit testing

**Comment by jodygarnett** [comment]
I guess a fix for this would be to better document how schema plugins are written and tested.

**Comment by ianwallen** [comment]
My eyes were playing games with me - I did not notice core vs schema-core.  My mistake ignore that issue.

Regarding the testResource - I believe some plugins have this and some don't. i.e. iso19115-3.2018, dublin-core.  
I find the reason I noticed is because Intellij treats test resources differently than the other (i.e. shades the files/folders different colors). This is a little annoying because when I'm writing new functionality, I can usually quickly identify if the file are from test/testResource files/folders and I will usually skip the test until I get the basic logic working.  By assigning production files as test, it voids this functionality in IntelliJ

**Comment by jodygarnett** [comment]
I see, it is indeed inconsistent with IntilliJ practice.

While I cannot think of a quick fix, here is an approach:

* Register `src/main/plugin/iso19139.ca.HNAP` folder as `resource`, it would I suspect be available for testing, and show up as source content in IntilliJ
* make a custom jar assembly that excludes this content
* the content is already packaged in custom zip assembly

**Comment by ianwallen** [comment]
@jodygarnett 

I believe that approach would work.  And your suspicions are correct that it should be available for testing.

**Comment by jodygarnett** [comment]
Okay, that way would work but was a lot of work duplicating the `jar` assembly. Eventually I found an easier approach configuring the `maven-jar-plugin`:

````
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <excludes>
            <!-- ignore schema-plugin content -->
            <exclude>convert/**</exclude>
            <exclude>formatter/**</exclude>
            <exclude>index-fields/**</exclude>
            <exclude>layout/**</exclude>
            <exclude>loc/**</exclude>
            <exclude>present/**</exclude>
            <exclude>process/**</exclude>
            <exclude>sample-data/**</exclude>
            <exclude>schema/**</exclude>
            <exclude>schematron/**</exclude>
            <exclude>templates/**</exclude>
            <exclude>*.xsl</exclude>
            <exclude>*.xml</exclude>
            <exclude>*.xsd</exclude>
          </excludes>
        </configuration>
      </plugin>
```` 

And no longer displayed as testResource:

![image](https://user-images.githubusercontent.com/629681/99936773-ca370300-2d18-11eb-8b82-e0fd5ab808a7.png)
