### ISSUE TITLE
Replacing nap.geogratis.gc.ca service with schemas.metadata.geo.ca 

### ISSUE THREAD

**Issue by jodygarnett** [metadata101/iso19139.ca.HNAP#118]
The http://nap.geogratis.gc.ca/ server is decommissioned making this issue now critical (ie actively broken) and the metadata documents being published cannot be used by external tools.  We are looking for a 5 to 10 year decision here, although realistically documents like these do not expire and are useful as a historical record.

Some good ideas from meeting (following the OGC opengis and w3c example layout):

@bo-lu has access to `geo.ca` domain will request ``schemas.geo.ca``:
* https://schemas.geo.ca/iso19139.HNAP/1.2
* https://schemas.geo.ca/iso19139.HNAP/2.3.1
* Backed by a Government of Canada github repository (for groups to update via pull request).

The other idea is to setup GitHub pages ``metadata101.github.io/schemas``:

* https://metadata101.github.io/schemas/iso19139.HNAP/1.2
* https://metadata101.github.io/schemas/iso19139.HNAP/2.3.1
* repo would be available for use by any of the metadata 101 schemas

# Original: Schema location for hnap version 1.2 and 2.3.1, replacing http://nap.geogratis.gc.ca/

The *Metadata configuration* configuration validation to remove schema location for validation is required to validate records that have been generated by geonetwork.

![image](https://user-images.githubusercontent.com/629681/98129024-7f3e7400-1e6d-11eb-926c-fb445266f237.png)

Notes:

* remove schema location for validation removes the schemaLocation from the xml editor when validation button is pressed
* exporting always generates schemaLocation information (when record is downloaded as xml)
* Records downloaded as xml, do not subsequently validate (when imported back into geonetwork again)

Generated schemaLocation information:

* http://www.isotc211.org/2005/gmd
* http://nap.geogratis.gc.ca/metadata/tools/schemas/metadata/can-cgsb-171.100-2009-a/gmd/gmd.xsd
* http://www.isotc211.org/2005/srv http://nap.geogratis.gc.ca/metadata/tools/schemas/metadata/can-cgsb-171.100-2009-a/srv/srv.xsd
* http://www.geconnections.org/nap/napMetadataTools/napXsd/napm
* http://nap.geogratis.gc.ca/metadata/tools/schemas/metadata/can-cgsb-171.100-2009-a/napm/napm.xsd

Example: 
```
<?xml version="1.0" encoding="UTF-8"?>
<gmd:MD_Metadata xmlns:gml="http://www.opengis.net/gml/3.2"
                 xmlns:gco="http://www.isotc211.org/2005/gco"
                 xmlns:gmd="http://www.isotc211.org/2005/gmd"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xmlns:gfc="http://www.isotc211.org/2005/gfc"
                 xmlns:gmi="http://www.isotc211.org/2005/gmi"
                 xmlns:gsr="http://www.isotc211.org/2005/gsr"
                 xmlns:gmx="http://www.isotc211.org/2005/gmx"
                 xmlns:xlink="http://www.w3.org/1999/xlink"
                 xmlns:gss="http://www.isotc211.org/2005/gss"
                 xmlns:uuid="java:java.util.UUID"
                 xmlns:srv="http://www.isotc211.org/2005/srv"
                 xmlns:gts="http://www.isotc211.org/2005/gts"
                 xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://nap.geogratis.gc.ca/metadata/tools/schemas/metadata/can-cgsb-171.100-2009-a/gmd/gmd.xsd http://www.isotc211.org/2005/srv http://nap.geogratis.gc.ca/metadata/tools/schemas/metadata/can-cgsb-171.100-2009-a/srv/srv.xsd http://www.geconnections.org/nap/napMetadataTools/napXsd/napm http://nap.geogratis.gc.ca/metadata/tools/schemas/metadata/can-cgsb-171.100-2009-a/napm/napm.xsd">
```

With *remove schema location for validation* `true`, when validating the `xsi:schemaLocation` above are removed (and geonetwork is able to validate the file).

**Comment by josegar74** [comment]
The problem I think is that online xsd are not updated in http://nap.geogratis.gc.ca/ server, containing old versions.

Alternatively an option can be to define the schema location to use the local xsd's. For example for iso19139, in this test server: https://vanilla.geocat.net/geonetwork/xml/schemas/iso19139/schema/gmd/gmd.xsd, but probably requires some code changes to be able to replace the url of the server as usually this information is defined in the @schema-ident.xml@ file of the schema.

**Comment by jodygarnett** [comment]
Thanks, I have updated the description to be more clear.

Just to confirm this is an hnap problem, and not something to report to core-geonetwork?

**Comment by jodygarnett** [comment]
Notes:

* The http://nap.geogratis.gc.ca/metadata/tools/schemas/metadata/can-cgsb-171.100-2009-a/ is publishing from 2013, our internal ones use versions from 2012
* Not in a position to upgrade without coordination with DFO, FGP, ECC, etc...
* Pointing to vanilla.geocat.net is probably not good, but we could reference an FGP server (for example)

Ideas:

* Consider talking to http://nap.geogratis.gc.ca/ about managing multiple versions? If it is maintained ...
* Consider publishing for public on opendata server? Or with another department ....

**Comment by jodygarnett** [comment]
Notes:

* @ianwallen has a PR to upgrade to the 2013 schemas above, but this requires coordination across DFO, ECCC, FGP

**Comment by ianwallen** [comment]
I did do a branch that performs the upgrade.
https://github.com/ianwallen/iso19139.ca.HNAP/tree/NAP_upgrade_2013
Not sure if upgrading will cause any issues.

**Comment by jodygarnett** [comment]
Other examples of "internal" changes that may or may not provide value:

* See https://github.com/metadata101/iso19139.ca.HNAP/issues/112 email manditory, rather than optional
* Multilingual phone number and email address

**Comment by jodygarnett** [comment]
Assigning to @bo-lu and @geothorne to coordinate a course of action:

* option 1: Upgrade HNAP from 2012 to 2013, would manage all branches as per NAP_upgrade_2013 above
* option 2: Publish the HNAP 2012 schemas somewhere (negotiate with nap.geogratis.gc.ca or provide a public server)

**Comment by ianwallen** [comment]
If this issue is fixed then I believe it will also fix issue #89

**Comment by jodygarnett** [comment]
Discussion on where to publish:

* As a group we have access to http://nap.geogratis.gc.ca/metadata/tools/schemas/ server
* The server is being replaced, so a new server will need to take over this domain
* The structure above appears to be accidental, cannot figure out the naming convention
  
  * http://nap.geogratis.gc.ca/metadata/tools/schemas/metadata/can-cgsb-171.100-2009-a/
  
  Ideally we will continue the above folder for existing users, but note it is not used currently by FGP.

* Consider http://schemas.opengis.net/wfs/ example with different 1.0 and 1.1 folders

Propose folder structure based on year or version number from *HNAP Proposed Updates 2.3.1* document:

* http://nap.geogratis.gc.ca/schemas/iso19139.ca.HNAP/1.2
* http://nap.geogratis.gc.ca/schemas/iso19139.ca.HNAP/2.3.1

napm.xsd has version:

```
<xs:schema
  targetNamespace="http://www.geconnections.org/nap/napMetadataTools/napXsd/napm"
  xmlns:gmd="http://www.isotc211.org/2005/gmd"
  elementFormDefault="qualified"
  version="2013-02-22"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:napm="http://www.geconnections.org/nap/napMetadataTools/napXsd/napm">
```

gmd.xsd has version:

```
<xs:schema
   targetNamespace="http://www.isotc211.org/2005/gmd"
   elementFormDefault="qualified"
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xmlns:gmd="http://www.isotc211.org/2005/gmd"
   version="2012-07-13">
```

**Comment by jodygarnett** [comment]
@bo-lu this requires some though and a decision ahead of server being shut off.

**Comment by jodygarnett** [comment]
@bo-lu from last meeting it seems a service can be setup at this location (once the present server is decommissioned).

We still have this issue capturing that the schema included with the hnap schema plugin does not match what is published.

**Comment by jodygarnett** [comment]
I would like to propose following the OGC example of publishing schemas by version number:

* http://schemas.opengis.net/wfs/1.0.0/
* http://schemas.opengis.net/wfs/1.1.0/
* http://schemas.opengis.net/wfs/1.1/
* http://schemas.opengis.net/wfs/2.0/

We can then support the two schema presently known, and allow for future versions:

http://nap.geogratis.gc.ca/schemas/iso19139.ca.HNAP/1.2
http://nap.geogratis.gc.ca/schemas/iso19139.ca.HNAP/2.3.1

**Comment by jodygarnett** [comment]
A suggestion was made to use  an official GC github to host the above.

**Comment by bo-lu** [comment]
I will ask if we can use: https://github.com/Canadian-Geospatial-Platform

**Comment by jodygarnett** [comment]
We should try an experiment and then make a recommendation to HNAP team (who has governance over the standard and this location).

**Comment by jodygarnett** [comment]
Use of github directly is not the best, the file:

* https://Canadian-Geospatial-Platform/hnap/blob/master/schemas/iso19139.ca.HNAP/2.3.1/gmd.xsd

Is accessed as:

* https://raw.githubusercontent.comCanadian-Geospatial-Platform/hnap/schemas/iso19139.ca.HNAP/2.3.1/gmd.xsd

Could also look at:

* Github pages:  https://Canadian-Geospatial-Platform.github.io/hnap/schemas/iso19139.ca.HNAP/2.3.1/gmd.xsd
* Github packages: not sure if this does `xsd` files need to check

**Comment by bo-lu** [comment]
My take is that we can host the schema files on 'geo.ca' and create a github repository for issue tracking and fixes (i.e., via pull requests).

**Comment by jodygarnett** [comment]
The the previous server decommissioned this issue is now critical (ie actively broken) and the metadata documents being published cannot be used by external tools.  We are looking for a 5 to 10 year decision here, although realistically documents like these do not expire and are useful as a historical record.

Some good ideas from meeting (following the OGC opengis and w3c example layout):

@bo-lu has access to `geo.ca` domain will request ``schemas.geo.ca``:
* https://schemas.geo.ca/iso19139.HNAP/1.2
* https://schemas.geo.ca/iso19139.HNAP/2.3.1
* Backed by a Government of Canada github repository (for groups to update via pull request).

As a fall back plan we could setup GitHub pages ``metadata101.github.io/schemas``:

* https://metadata101.github.io/schemas/iso19139.HNAP/1.2
* https://metadata101.github.io/schemas/iso19139.HNAP/2.3.1
* repo would be available for use by any of the metadata 101 schemas

**Comment by jodygarnett** [comment]
I am checking if osgeo can provide hosting (so we can avoid GitHub in the URL) https://trac.osgeo.org/osgeo/ticket/2594

**Comment by jodygarnett** [comment]
The new location is shaping up https://github.com/metadata101/schemas

Notes above indicate version `2.3.1`(geogratis) and `1.2` (hnap schema plugin) but I am having trouble finding these version numbers in the schema output.

Some work remains for gitub pages to publish `xsd` files as assets, and to revert some edits that have been made over time (hard coding geogratis links).

**Comment by jodygarnett** [comment]
Breakout review of https://hnap.schemas.metadata.geo.ca/metadata and comparison with https://schemas.opengis.net/

hnap.schemas.metadata.geo.ca
- this is a lift and shift of the geogratis http://nap.geogratis.gc.ca/metadata/
- top-level registry folder links out to official iso locations ``register/iso19135-2-2012/``
- top-level metadata folder is grouped by standard ``metadata/can-cgsb-171.100-2009-a/``

schemas.opengis.net
- has directory structure named by standard and then version
- no duplication which is nice (two standards can reference the same gml/2.1.2/gml.xsd
- contains readme, and zip downloads, and other supporting documenation

Approach:
- make a folder for each "external" organization (``iso``)
- take the folder structure approach of schemas.opengis.net (``can-cgsb``, ``gml``)
- take the version number structure of schemas.opengis.net (``2.0.1`` gml, ``2.3.1`` hnap)
- use canadian standard number for NAP ``can-cgsb-171.100-2009-a``

**Comment by jodygarnett** [comment]
Canadian standard number format: Number - subject area, standard number, year of publication.

* ``171`` geospatial subject area
* ``100`` is HNAP
* ``2009`` year of publication
* ``a``

This looks like for external schemas:

* ``ogc/gml/2.01``
* ``iso/19115/2003``
* ``iso/19115/2003/README.md`` - document exact version used and changelog
* ``iso/19135/`` - register folder 
* ``iso/19139/``

If we ignore the ``201.100`` as assumed:

* ``2009a/2.3.1/``
* ``2009a/2.4/`` - proposed changes/clarifications

**Comment by jodygarnett** [comment]
This results in (if we can drop `hnap` from subdomain):

* ``https://schemas.metadata.geo.ca/2009a/2.3.1/register.xsd``
* ``https://schemas.metadata.geo.ca/2009a/2.3.1/napm/napm.xsd``

Actions:

* [x] can we remove hnap from subdomain
* [x] can use markdown readme
* [x] try out folder structure locally, to ensure we can validate against it
* [ ] check what is required to update existing metadata records (simple search and replace)
* [ ] check if geogratis forward is appropriate / will work

**Comment by bo-lu** [comment]
How should we configure it so that geogratis is permanent redirected?

**Comment by jodygarnett** [comment]
It depends what software is presently serving geogratis and the new service.


1. If the service is still operational, and using something like apache, then individual files can be redirected to their new schemas.metadata.geo.ca location.

* http://nap.geogratis.gc.ca/metadata/tools/schemas/metadata/can-cgsb-171.100-2009-a/napm/napm.xsd
  
  https://schemas.metadata.geo.ca/2009a/2.3.1/napm/napm.xsd 

2. If the service is decommissioned completely a domain redirect can be established to the new location.

* http://nap.geogratis.gc.ca/*
  
  https://schemas.metadata.geo.ca/*

  So all incoming requests will be redirected to schemas.metadata.geo.ca .

3) If the new service is running something like apache then it can be setup to respond to the redirects from the previous domain (step 2 above), and redirect to the new file by file location.

* https://schemas.metadata.geo.ca/metadata/tools/schemas/metadata/can-cgsb-171.100-2009-a/napm/*
  
  https://schemas.metadata.geo.ca/2009a/2.3.1/napm/*

The redirect should respond with a ``HTTP/1.1 301 Moved Permanently`` indicating the new location of the file.

We can dig into this once we have new service to experiment with.

Although setting up a web service to redirect files is straightforward; configuring an xml parser to follow such redirects is not very common; and can also be considered a [security vulnerability](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html).  With this in mind setting up redirects may not reliably allow existing datasets downloaded the public to be validated without modification of the file (or the code reading the file).

**Comment by jodygarnett** [comment]
Note in HNAP all the schema namesapces are ``http`` this does not have to be ``https`` as it is only a URI.

The schema location will change from geogratis to a https location.

See: https://stackoverflow.com/questions/30707609/xml-namespace-uri-with-https

**Comment by jodygarnett** [comment]
Identified a number of ``metadata/register/`` files referenced in code lists and examples:

```xml
<gmd:LanguageCode codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_116"
  codeListValue="{$mainLanguage}">
```

```rst
**Guideline:** characterSet shall use codelist [napMD_CharacterSetCode]
(http://nap.geogratis.gc.ca/metadata/register/codelists-eng.html#IC_95). Value will be “utf8; utf8”.
```

**Comment by jodygarnett** [comment]
Update:

- https://schemas.metadata.geo.ca/home.html
- the ``html`` content is migrated https://schemas.metadata.geo.ca/metadata/register/codelists-eng.html#IC_95

**Comment by jodygarnett** [comment]
The code list is a URI, however recommended to resolve this as a URL (to match how ISO19139 works):

```xml
<gmd:LanguageCode codeList="https://schemas.metadata.geo.ca/metadata/register/napMetadataRegister.xml#IC_116"
  codeListValue="{$mainLanguage}">
```

This is a change to the content of our records durning migration; previously we were just changing the schemaLocation at the top of the files (not the content).

**Comment by jodygarnett** [comment]
Branch is here: https://github.com/metadata101/iso19139.ca.HNAP/tree/transition_schemas_metadata_geo_ca

I am testing on 4.2.x before proposing backport.
