### ISSUE TITLE
Extent Description field does not show up in the Basic View

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#122]
Extent Description field is and option HNAP field.  If a value is entered from the advanced view, the value does  not show up in the Basic View

As this is part of the HNAP fields, it should display in the basic view.

**Comment by ianwallen** [comment]
I have tried to edit the config-editor.xml file to add the field however I cannot figure out how to add the field.

**Comment by ianwallen** [comment]
I have attempted to show the gmd:extent/*/gmd:description on the basic editor by adding the following to the config-editor.xml

```
          <field xpath="/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:description"
                   in="/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent"
                   or="description"/>
```

The field does not show up because of the following lines of code in the iso19139.

https://github.com/geonetwork/core-geonetwork/blob/master/schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl#L306-L314

```
  <!-- In flat mode do not display geographic identifier and description
  because it is part of the map widget - see previous template. -->
  <xsl:template mode="mode-iso19139"
                match="gmd:extent/*/gmd:description[$isFlatMode]|
                       gmd:geographicElement[
                          $isFlatMode and
                          preceding-sibling::gmd:geographicElement/gmd:EX_GeographicBoundingBox
                        ]/gmd:EX_GeographicDescription"
                priority="2000"/>
```

According to the comment, the description is part of the map widget however I cannot locate the description fields within the map widget.

1 - Is this a bug in iso19139 where the description is no longer supported in the map widget and the above code should be corrected to exclude the gmd:description from the condition.
2 - is there a configuration option for the map widget to add the description? If so where?

Thank you

**Comment by ianwallen** [comment]
@josegar74 would you be able to answer the 2 questions I have in the last comment?

Thank you

**Comment by josegar74** [comment]
In ISO19139 editor, it's displayed properly:

![mapwidget-description](https://user-images.githubusercontent.com/1695003/98906701-dcfe3c00-24bd-11eb-9984-10ef7aab71b8.png)

This code handles it:

https://github.com/geonetwork/core-geonetwork/blob/21457610e173327bc8f0637ef330bc80241d7d51/schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl#L261-L266

```
          <xsl:if test="$description and $isFlatMode and not($metadataIsMultilingual)">
            <xsl:attribute name="data-description"
                           select="$description"/>
            <xsl:attribute name="data-description-ref"
                           select="concat('_', $description/gn:element/@ref)"/>
          </xsl:if>
```

The problem seem the multilingual check, seem the map widget is not updated to use the multilingual field widget if this field requires to be multilingual.

Does HNAP requires this field to be multilingual? If not, can be changed easily to check also if the field is multilingual using `config-editor.xml` configuration). If requires to be multilingual requires also changes in the `gnDrawBbox` directive.

**Comment by ianwallen** [comment]
@josegar74 
I attempted to add this code however the issue with the widget is that it does not support multilingual descriptions as it has 
`and not($metadataIsMultilingual)`

So I have created a PR https://github.com/geonetwork/core-geonetwork/pull/5185 to update the iso19139 so that it does not remove the gmd:description if it is multilingual.
