### ISSUE TITLE
Some translation required

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#128]
Looking at the following location I can see that there are still some English text that needs some French translation.

https://github.com/metadata101/iso19139.ca.HNAP/tree/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre

i.e. 
https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/schematron-rules-common.xml#L24

https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/schematron-rules-common.xml#L29

https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/schematron-rules-multilingual.xml#L14-L27

Someone will need to go over the files in this folder and ensure that translation has been done.

**Comment by wangf1122** [comment]
> Looking at the following location I can see that there are still some English text that needs some French translation.
> 
> https://github.com/metadata101/iso19139.ca.HNAP/tree/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre
> 
> i.e.
> https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/schematron-rules-common.xml#L24
> 
> https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/schematron-rules-common.xml#L29
> 
> https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/schematron-rules-multilingual.xml#L14-L27
> 
> Someone will need to go over the files in this folder and ensure that translation has been done.



> Looking at the following location I can see that there are still some English text that needs some French translation.
> 
> https://github.com/metadata101/iso19139.ca.HNAP/tree/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre
> 
> i.e.
> https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/schematron-rules-common.xml#L24
> 
> https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/schematron-rules-common.xml#L29
> 
> https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/schematron-rules-multilingual.xml#L14-L27
> 
> Someone will need to go over the files in this folder and ensure that translation has been done.

The none multilingual also has some untranslated text.

https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/schematron-rules-non-multilingual.xml

**Comment by ianwallen** [comment]
@wangf1122 
Did https://github.com/metadata101/iso19139.ca.HNAP/pull/149 resolve all the translation issues. Can we close this issue?

**Comment by wangf1122** [comment]
> @wangf1122
> Did #149 resolve all the translation issues. Can we close this issue?

Yes, we can close this issue.
