### ISSUE TITLE
bundle hnap user manual as docs folder, publish online as github pages for this repository

### ISSUE THREAD

**Issue by jodygarnett** [metadata101/iso19139.ca.HNAP#132]
I would like to propose an hnap user manual, using the following structure:

* `docs/` published as github pages (a repository settings change option rather than `gh-pages` branch)
* `src/sphinx` sphinx `rst` documentation
* `pom.xml` goals to to build docs if sphinx-build installed and publish into docs folder

# user documentation

User focused documentation in contrast the the geonetwork user manual which combines information for visitors, editors and administrators (sometimes in a single paragraph!)

![image](https://user-images.githubusercontent.com/629681/99753525-34427480-2a9b-11eb-8f71-4aed1cc57938.png)

Working on [writing guidelines](https://geocat.github.io/geocat-themes/) to keep documentation consistent and gradually improve the geonetwork user manual.

# runtime documentation

In addition to publishing using github pages above, this documentation could be included in the running geonetwork application (for example accessed by a link in the application footer.)

Note `core-geonetwork` already publishes documentation added to the `geonetwork` web app `doc` folder, we are just  taking over this functionality to include a user manual rather than the community docs.

# maintenance

Reviewing other active schema plugins:

*iso19139*: possibility to share general content such as how to search, view and download records. Large range of translations desirable. Long term it may be desirable to setup iso19139 documentation as a base, and use maven to carefully add additional pages. 

*dutch schemas*: Likely only needed in the dutch language, make use of a specific dutch skin so unlikely to collaborate on iso19139 content above.

# Draft structure

```
FILE               TITLE
index              User Manual
search/index       Catalogue
search/records     Search records
search/detail      View Record
search/download    Download record
editor             Editor
editor/edit        Edit
editor/validation  Validation
editor/publish     Publish
editor/create      Create
admin              Administration
admin/settings     Settings
```

The above draft structure is what I have on hand to start the activity. Adding additional pages to cover `editor/workflow` can be added over time. The docs use sphinx external links to link to the geonetwork docs as reference material.

**Comment by ianwallen** [comment]
I believe this is a good idea but I believe we want to avoid duplicating content that should be in the main geonetwork docs as it will be difficult to maintain.

I believe we should submit suggestions to the geonetwork doc repo to remove administrative tasks from the user guide and clean it up..   I do agree that there is some content in the user guide that may confuse the general users and it should be moved elsewhere.   

I do like your layout better than the GN docs however it would be nice to merge the gn docs with your to generate a flow tree so we could see the big picture.
i.e. Geonetwork docs have information on classification/workflow/exporting/associating resource... do you see that as being under your editor tab?  While using the map may be part of the search.

Then I think we should attempt to align ourselves to the geonetwork doc folder structure and have it so that we can contribute the HNAP specific docs by adding an entry to the pom - similar to how it is done in Geonetwork core. (open to alternative options)

**Comment by jodygarnett** [comment]
I am not sure about overlapping with geonetwork docs, viewing it more as a reference manual than a user guide at present.

We can discuss the table of contents if there is interest in pursing this. 
- searching is really all the stuff a website visitor can do. So has information on using classification to filter results, or the facets to quickly search content. And has information on exporting records as zips, or pdfs, or xml.
- editor has information for editors. I would make a distinct page for workflow review (as not every site has workflow turned on).
- following this model a review page would have information for reviewers etc...

**Comment by fxprunayre** [comment]
Not sure it can help, but FYI, some time ago for Wallonia region which is using custom editor views we also tried to build editor documentation based on the configuration of the editor (see https://github.com/geonetwork/core-geonetwork/tree/master/docs/schema-doc/src/main/resources and https://github.com/geonetwork/core-geonetwork/tree/master/schemas/iso19139/doc) with screenshots, XML snippet and instructions. Doing this also force to improve tooltip helps, labels, cleanup unused codelist values ... We had similar discussions about how to link to other sections of the doc eg. associating resource ... but we did not really finalized that work.

The current output for a standard like ISO19139 is probably too technical (https://geonetwork-opensource.org/manuals/trunk/en/annexes/standards/iso19139.html), but when having more customized thematic editor with instructions, the editor guide could probably much more attractive and useful for end users:

![image](https://user-images.githubusercontent.com/1701393/99879763-26adfb80-2c0f-11eb-867c-fa083884a678.png)

That part was more focus on editor manual without overlapping with the general editor doc.

**Comment by jodygarnett** [comment]
That is really cool @fxprunayre!

So if I understand correctly that is overriding some screen snaps, and `rst-writer.xsl` to generate out rst for sphinx to use. 🆒 

I was thinking something similar to how OSGeoLive handles translations:

iso19139:
```
src/sphinx/index.rst
src/sphinx/section1/index.rst
src/sphinx/section1/img/screen_snap.png
``` 

iso19139.ca.HNAP:
```
src/sphinx/index.rst (replaces index page and ads some new toctree pages)
src/sphinx/section1/img/screen_snap.png (override screen snap showing hnap content)
src/sphinx/section2/index.rst (this is a new page)
src/sphinx/section2/img/screen_snap.png (new page has its own screen snaps)
```

For context the above proposal is to do this at a community level, rather than build up addition docs exclusive to our [enterprise product](https://www.geocat.net/docs/geonetwork-enterprise/2020.5/index.html).

**Comment by jodygarnett** [comment]
This is now available: https://metadata101.github.io/iso19139.ca.HNAP/

![image](https://user-images.githubusercontent.com/629681/105017256-6cf9be00-59f8-11eb-8fc7-76e4030bec44.png)

Next steps will be setting up for translation, and gradually filling in more stories.
