### ISSUE TITLE
Metadata with French as the main languages are not showing proper language in display

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#147]
There is a new metadata template with French as the main language "Profile - HNAP Level 1 (French)"/"Profile - PNAH niveau 1 (française)"

When looking at the list of templates with the ui set to English - I would expect to see  "Profile - HNAP Level 1 (French)" but I get the French.

![image](https://user-images.githubusercontent.com/1868233/101067315-c81d4180-356d-11eb-827a-a56526d6cd3e.png)

![image](https://user-images.githubusercontent.com/1868233/101067149-9310ef00-356d-11eb-8694-5c0fdc5fae14.png)

Also the default display in English also show other French data.

![image](https://user-images.githubusercontent.com/1868233/101067764-4bd72e00-356e-11eb-82e2-fbe3bcda0d02.png)

Oddly, if I used the formatter such as "/formatters/xsl-view?root=div&view=default" then it displays as expected.

![image](https://user-images.githubusercontent.com/1868233/101067955-8214ad80-356e-11eb-9984-62423c48b72b.png)

**Comment by josegar74** [comment]
In the index folder I have 3 subfolders: `eng`, `fre` and `$isolangid`, the english version of the metadata is stored in `$isolangid` instead of the folder `eng`, seem some issue processing the alternative language

**Comment by josegar74** [comment]
The problem is this code:

https://github.com/metadata101/iso19139.ca.HNAP/blob/6275428962441412652244020c4d9fd5860ecb2d/src/main/plugin/iso19139.ca.HNAP/index-fields/language-default.xsl#L91

Going to fix directly in the branch

**Comment by josegar74** [comment]
@ianwallen please update, should be fine now

**Comment by ianwallen** [comment]
@josegar74 
Thank you for the quick resolution 

Looks like there is another occurrence of `<xsl:otherwise>$isoLangId</xsl:otherwise> ` on line 130.

I will fix that one shortly.

Thank you
