### ISSUE TITLE
How to change default view?

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#148]
I changed the defaultview to `/formatters/xsl-view?root=div&view=default`

![image](https://user-images.githubusercontent.com/1868233/101072042-c6ef1300-3573-11eb-9f5c-6ee982b172ef.png)

But when I search and click on a record it will still only show the standard view.

I can then go to  display and select default view to have it changed.

![image](https://user-images.githubusercontent.com/1868233/101072403-5ac0df00-3574-11eb-82b1-d955ab26f2a5.png)

How can I make the "Default view" show up by default when viewing a record?  Is this possible?

**Comment by josegar74** [comment]
Seem this property it's not available in the UI Settings page directly: http://SERVER/geonetwork/srv/eng/admin.console#/settings/ui, but can be edited in the JSON at the bottom of the page. Search for the following snippet:

```
"formatter": {
    "list": [
      {
        "label": "defaultView",
        "url": ""
      },
      {
        "label": "full",
        "url": "/formatters/xsl-view?root=div&view=advanced"
      }
    ],
    "defaultUrl": ""
},
```

Change `defaultUrl` to `/formatters/xsl-view?root=div&view=advanced` and save the UI settings.

**Comment by ianwallen** [comment]
@josegar74 
If I change the defaultUrl it only partially works.
I'm able to search for records and then when I click to view them they use the defaultUrl
But if I go to the editor board and click on the link to go to the metadata record - it uses the previous default.

The link from the main search page give the following link.
`/geonetwork/srv/eng/catalog.search#/metadata/e0722ad7-0374-4267-93b2-fbb4966a4b51/formatters/xsl-view?root=div&view=default`

The link from the editor board page gives the following link
`/geonetwork/srv/eng/catalog.search#/metadata/e0722ad7-0374-4267-93b2-fbb4966a4b51`

Maybe the system should have done a redirect when the formatter did not exists?  Maybe this still needs some work?

**Comment by josegar74** [comment]
I tested and this url seem used only from the search results, from the Editor dashboard, the link in the title uses `/geonetwork/srv/eng/catalog.search#/metadata/e0722ad7-0374-4267-93b2-fbb4966a4b51`.

Also editing from the metadata detail page displaying the full view I see the following url:

`/geonetwork/srv/eng/catalog.edit#/metadata/62373?redirectUrl=catalog.search%23%2Fmetadata%2Fe0722ad7-0374-4267-93b2-fbb4966a4b51

the `redirectUrl` parameter doesn't use the formatter url.

It seems the property it is not used in all places that display the metadata detail page.
