### ISSUE TITLE
French title not showing up correctly

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#16]
If I upload the following file and go to the viewer (taken from FGP/Open Data) and go to the viewer

The English Title looks correct but the French title is incorrect.  It also seems like it is a json array with duplicate values.

["Cartographie des débarquements de la pêche côtière du homard et de l'effort de pêche sur un quadrillage statistique de la région des Maritimes (2012 à 2014)","Cartographie des débarquements de la pêche côtière du homard et de l'effort de pêche sur un quadrillage statistique de la région des Maritimes (2012 à 2014)"]

I have attempted to debug this with no luck.  

I included a sample of the xml file that was uploaded.

[64f741d7-1129-49dd-9e5c-2b1de79024f0.zip](https://github.com/metadata101/iso19139.ca.HNAP/files/4377233/64f741d7-1129-49dd-9e5c-2b1de79024f0.zip)

The record also exist on open data.
https://open.canada.ca/data/en/dataset/64f741d7-1129-49dd-9e5c-2b1de79024f0

This is affecting the 3.8 and 3.10 branch - did not test 3.6

**Comment by ianwallen** [comment]
Found bug - it is related to textgroup title being indexed twice.  I will work on a fix shortly.

**Comment by josegar74** [comment]
I have tried also the iso19139 approach (as described in the PR #26), but indeed something else seem missing as doesn't solve the problem. 

Merged the PR as looks working fine, to investigate further.

Let me know if you'll cherry-pick to 3.10.x or want me to do it, then we can close the issue.

**Comment by ianwallen** [comment]
I have done a cherry-pick of the commit to 3.10.x branch.
Closing the issue.
