### ISSUE TITLE
Exported ISO19139 meta file is lacking of some namespaces

### ISSUE THREAD

**Issue by wangf1122** [metadata101/iso19139.ca.HNAP#172]
1) Take a meta data that passes the validation. The MD_Metadata contains these namespace (i.e. xmlns:napm is used in fileType)

![image](https://user-images.githubusercontent.com/74916635/105394179-3fc13180-5beb-11eb-8b80-fe5edbdcfdb1.png)

2) Do an export of the this meta as zip file. Pick the ISO19139.xml to brose.
![image](https://user-images.githubusercontent.com/74916635/105394388-80b94600-5beb-11eb-8d43-caf4581ce296.png)

3) All other namespaces except xmlns:gmd are gone.

![image](https://user-images.githubusercontent.com/74916635/105394508-ad6d5d80-5beb-11eb-944c-114c35f49619.png)

These namespace loss can cause problem to other system (i.e. FGP) during their validation stage.

**Comment by wangf1122** [comment]
A pull request is made to correct this issue.

https://github.com/metadata101/iso19139.ca.HNAP/pull/174

**Comment by ianwallen** [comment]
@wangf1122  - I believe this issue is fixed - closing the issue.
