### ISSUE TITLE
3.10.6 Release

### ISSUE THREAD

**Issue by jodygarnett** [metadata101/iso19139.ca.HNAP#175]
I would like to release a 3.10.6 based on the core-geonetwork 3.10.6 release last week.

There is one outstanding pull-request, anything else that should be addressed?

**Comment by ianwallen** [comment]
All PR's have been merged - feel free to create the 3.10.6 release when you are ready.

**Comment by jodygarnett** [comment]
Thanks @ianwallen, just finishing up some actual testing (want to make sure the docs are packaged, and install instructions updated).
