### ISSUE TITLE
Info - rd-alliance.org - RDA standard for data management plans as a template

### ISSUE THREAD

**Issue by geothorne** [metadata101/iso19139.ca.HNAP#176]
GeoNetwork supports  RDA standard for data management plans as a template?

ECCC is supporting a Government Wide GC application profile to have a data management plans.
If no, Could it support?

[www.rd-alliance.org - RDA Background Info](https://www.rd-alliance.org/group/dmp-common-standards-wg/outcomes/rda-dmp-common-standard-machine-actionable-data-management)

 [RDA standard - Git Project]( https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard)

**Comment by josegar74** [comment]
RDA standard seem a JSON based schema. GeoNetwork doesn't support it directly (it works only with XML formats). But there's a JSON schema definition provided in  https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/blob/master/examples/JSON/JSON-schema/1.1/maDMP-schema-1.1.json. An option it's to generate the XSD schema from the JSON schema with some tool, so GeoNetwork can manage it in XML format and provide an output as JSON.

**Comment by jodygarnett** [comment]
This may end up being supported by addition of ogc-api-records standard being developed this month.

**Comment by geothorne** [comment]
Thanks Jody, This all makes sense to me.
