### ISSUE TITLE
Contact information not correct 

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#18]
Contact information for the supplied sample metadata record does not show the contact information correctly.

It shows the following for English (RI_418 needs to be converted)

Government of Canada; Fisheries and Oceans Canada; Oceans and Coastal Management Division
**RI_418:**

And for French, there is no contact information.

[64f741d7-1129-49dd-9e5c-2b1de79024f0.zip](https://github.com/metadata101/iso19139.ca.HNAP/files/4377303/64f741d7-1129-49dd-9e5c-2b1de79024f0.zip)

Record also exists on open data - https://open.canada.ca/data/en/dataset/64f741d7-1129-49dd-9e5c-2b1de79024f0

**Comment by josegar74** [comment]
@ianwallen I merged to 3.8.x, let me know if you'll cherry-pick to 3.10.x or want me to do it, then we can close the issue.

**Comment by ianwallen** [comment]
I have cherry picked the changes to 3.10.x.
Closing the issue
