### ISSUE TITLE
Version issue when attempting to use newer HNAP

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#185]
I got the following error 

2021-02-18 08:59:17,233 ERROR [geonetwork.schemamanager] - Schema iso19139.ca.HNAP requires min Geonetwork version: 3.10.5, current is: 3.10-SNAPSHOT. Skip load schema.

And seem to be caused by the following lines.

https://github.com/metadata101/iso19139.ca.HNAP/blob/a1f26d73d543724e040b9f462fd83b4f56d5755a/src/main/plugin/iso19139.ca.HNAP/schema-ident.xml#L30-L31

If I change these to `3.10` then it seems to work.  
I also tried `3.10.6` - but it die not work? - Got the following error.

2021-02-18 09:34:17,906 ERROR [geonetwork.schemamanager] - Schema iso19139.ca.HNAP requires min Geonetwork version: 3.10.6, current is: 3.10-SNAPSHOT. Skip load schema.

@jodygarnett what should these values be set to? Should it be 3.10?  And if so how do we indicate that release 3.10.6 may not work on 3.10.4?

In either case 3.10.5 seems to be incorrect and should be modified.

**Comment by jodygarnett** [comment]
Discussion:
```
	<!-- hnap schema version -->
	<version>2.3.1</version>
	<appMinorVersionSupported>3.10.6</appMinorVersionSupported>
```

* version is of schema (see above)
* appMinorVersionSupported needs to adjust to 3.10-SNAPSHOT

**Comment by jodygarnett** [comment]
I am experimenting with including:
```
	<version>2.3.1</version>
	<appMinorVersionSupported>3.10-SNAPSHOT</appMinorVersionSupported>
```

The`` SchemaManager.checkSupported(schemaPluginCatRoot)`` method sees ``3.10-SNAPSHOT`` as ``3.10.0`` with is not quite what I would like (but I suppose it will work).

Thinking it through from schema-plugin perspective:

* schema plugin ``3.10-SNAPSHOT`` --> ``3.10.0`` means that the plugin will load against the live core-geonetwork ``3.10-SNAPSHOT`` series.
* During release when schema plugin ``3.10-SNAPSHOT`` is replaced with ``3.10.7`` it will match with core-geonetwork and ensure things work together.

Thinking it through the from core-geonetwork perspective:

* Snapshot of core-geonetwork and snapshot of schema plugin can be tested together
* During release they are both versioned together to match what is tested
* A snapshot build of core-geonetwork will show up as ``3.10.0`` and refuse to load any released schema plugins (probably a good thing).

**Comment by jodygarnett** [comment]
I have done both the quick fix (changing to 3.10-SNAPSHOT and trusting 3.10.0 order is okay) and the long fix respecting maven style version numbers.

**Comment by ianwallen** [comment]
regarding "During release they are both versioned together to match what is tested"

I would think that it would be possible to have
- 3.10.0 in the plugin and that would allow GN 3.10.snapshot and 3.10.0, 3.10.1, 3.10.2... to use it.
- 3.10.1 in the plugin and that would allow GN 3.10.snapshot and 3.10.1, 3.10.2... to use it.
- 3.10.2 in the plugin and that would allow GN 3.10.snapshot and 3.10.2... to use it.

So instead of using 3.10.snapshot in the plugin, I would think that we would keep it as the lowest version that is allowed. Since there was some changes in the structure I would think that we would have to use 3.10.6 right now.

But in the future when gn 3.12 is release, we should be able to use 3.12.0 and it should work for all 3.12 version until there are new dependencies from the GN core.

As @josegar74  mentioned yesterday, there may be a but in the version checking within GN to allow this to work correctly.  Hopefully it is fixed by the 3.12.0 release so that we can set this plugin version to 3.12.0 and then we don't need to modify it during each release.

**Comment by ianwallen** [comment]
Related to the following GN PR
https://github.com/geonetwork/core-geonetwork/pull/5452

**Comment by jodygarnett** [comment]
Discussing with @juanluisrp about how this is used to manage database updates, we could pull the compatibility from the database upgrade list.

Presently using `3.10-SNAPSHOT` is not so good for running database updates. In a sense it will always try running up to the highest 3.10.x number.

**Comment by juanluisrp** [comment]
I've added a couple of commits. to https://github.com/geonetwork/core-geonetwork/pull/5452. The first one is only formatting and cleanup of the code in `Version` class.

The second is related to how versions are interpreted in `DatabaseMigration` class. 
This fix the problem of migration with only major, minor and `SNAPSHOT` versions that are present between tags. For example if `pom.xml` version is `3.10-SNAPSHOT` (with `3.10.7` as the next release) and the database is `3.10.4` this change will execute migrations for `3.10.5`, `3.10.6` and `3.10.7` if they are mapped in the data_migration bean. Before the change no migrations were executed because it interpreted that `3.10-SNAPSHOT` was older than `3.10.4`.

**Comment by jodygarnett** [comment]
Thanks @juanluisrp that looks great! I hope the pull request and backport are accepted soon.
