### ISSUE TITLE
Need to update Core subject thesaurus to be similar to FGP

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#212]
Attempted to load data generated by the HNAP 3.10.x into FGP and we got the following error.

![image](https://user-images.githubusercontent.com/1868233/117328855-6ccbe400-ae6a-11eb-8f0d-6314f27edf93.png)

We should ensure that the thesaurus between FGP and HNAP 3.10.x are using the same core subject thesausus.

**Comment by ianwallen** [comment]
@bo-lu 
I have assigned this to you to do a quick compare the following thesaurus to FGP and maybe you can help us identify the main differences.
https://github.com/metadata101/iso19139.ca.HNAP/blob/3.12.x/src/main/config/codelist/local/thesauri/theme/GC_Core_Subject.rdf

Maybe you can upload the FGP core subject thesaurus.  It sound like the FGP version was recently upgraded so maybe it is the most recent version.

**Comment by jodygarnett** [comment]
Bo found you have a newer core subject thesaurus then is use on the 3.6.x branch. Are there any others that are out of sync?

I recommend we commit any thesaurus files that are needed to version control 3.12.x branch, and backport to 3.6.x.

**Comment by ianwallen** [comment]
Seems to up to date now with the following PR
https://github.com/metadata101/iso19139.ca.HNAP/pull/220
