### ISSUE TITLE
Title missing from the search engine after upgrade

### ISSUE THREAD

**Issue by wangf1122** [metadata101/iso19139.ca.HNAP#290]
After the upgrade, the search engine indexing has some error and causing metadata title missing.

![image](https://user-images.githubusercontent.com/74916635/195395346-be528b26-94e5-496f-b01a-9f396b960a43.png)

"idxMsg": "GNIDX-XSL||A sequence of more than one item is not allowed as the first argument of name() (<gmd:fileName/>, <gmd:fileDescription/>, ...)",

@josegar74 
This commit is suspected causing such issue. https://github.com/metadata101/iso19139.ca.HNAP/commit/90f1ebb2ec73baab7e21f047f7b22d0df3c9b483

I did revert this commit and reindexing and the problem will be gone.

**Comment by josegar74** [comment]
@wangf1122 I don't see any changes related to that fields, can you attach 1 metadata that has the problem to try it?

**Comment by wangf1122** [comment]
> @wangf1122 I don't see any changes related to that fields, can you attach 1 metadata that has the problem to try it?

I will need to reset my environment and this change and see if I can reindex the metadata with issues. Then I will download it for you.

FYI, I also have an observation. If you edit the bad data and cancel the editing, it will be good. Some indexing is happing at the background I believe.

**Comment by jodygarnett** [comment]
meeting actions: Share a sample record to show the problem.

**Comment by josegar74** [comment]
@wangf1122 

In the metadata provided I see the following:

```
      <gmd:graphicOverview>
        <gmd:MD_BrowseGraphic>
          <gmd:fileName>
            <gco:CharacterString>http://localhost:8080/geonetwork/srv/api/records/2bb98a09-5daf-42c4-94e8-e5de718b821d/attachments/germanbankthumb1.PNG</gco:CharacterString>
          </gmd:fileName>
          <gmd:fileDescription>
            <gco:CharacterString>large_thumbnail</gco:CharacterString>
          </gmd:fileDescription>
        </gmd:MD_BrowseGraphic>
      </gmd:graphicOverview>

      <gmd:graphicOverview>
        <gmd:MD_BrowseGraphic>
          <gmd:fileName>
            <gco:CharacterString>http://localhost:8080/geonetwork/srv/api/records/b7f81d4a-2cb6-4393-b35b-e536ec63e834/attachments/germanbankthumb1_s.png</gco:CharacterString>
          </gmd:fileName>
          <gmd:fileDescription>
            <gco:CharacterString>thumbnail</gco:CharacterString>
          </gmd:fileDescription>
          <gmd:fileType xsi:type="napm:napMD_FileFormatCode_PropertyType" codeList="http://nap.geogratis.gc.ca/metadata/register/registerItemClasses-eng.html#IC_115" codeListValue="RI_716">
            <gco:CharacterString>png; png</gco:CharacterString>
          </gmd:fileType>
        </gmd:MD_BrowseGraphic>
      </gmd:graphicOverview>

      <gmd:graphicOverview>
        <gmd:MD_BrowseGraphic>
          <gmd:fileName>
            <gco:CharacterString>http://localhost:8080/geonetwork/srv/api/records/b7f81d4a-2cb6-4393-b35b-e536ec63e834/attachments/germanbankthumb1.png</gco:CharacterString>
          </gmd:fileName>
          <gmd:fileDescription>
            <gco:CharacterString>large_thumbnail</gco:CharacterString>
          </gmd:fileDescription>
          <gmd:fileType xsi:type="napm:napMD_FileFormatCode_PropertyType" codeList="http://nap.geogratis.gc.ca/metadata/register/registerItemClasses-eng.html#IC_115" codeListValue="RI_716">
            <gco:CharacterString>png; png</gco:CharacterString>
          </gmd:fileType>
        </gmd:MD_BrowseGraphic>
      </gmd:graphicOverview>
```

See the 2on and 3rd thumbnail elements,  containing the following:

```
   <gmd:fileType xsi:type="napm:napMD_FileFormatCode_PropertyType" codeList="http://nap.geogratis.gc.ca/metadata/register/registerItemClasses-eng.html#IC_115" codeListValue="RI_716">
            <gco:CharacterString>png; png</gco:CharacterString>
          </gmd:fileType>
```

The problem it's related to this element, I remember that type of element in HNAP, mixing a codelist and a text element, not following the standard way to describe codelists in iso19139.

I'll do a PR fixing the issue.

**Comment by josegar74** [comment]
@wangf1122 please try https://github.com/metadata101/iso19139.ca.HNAP/pull/291

**Comment by wangf1122** [comment]
> @wangf1122 please try #291

Confirmed and its working
