### ISSUE TITLE
Issue with reference to namespace geconnections

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#342]
Should the following uri
`http://www.geconnections.org/nap/napMetadataTools/napXsd/napm`

be changed to the following?
`https://schemas.metadata.geo.ca/2009/napm`

Related to PR #324 

Example:
https://github.com/metadata101/iso19139.ca.HNAP/blob/43efe958be6b8eb18acec2372e945056037b18e2/src/main/plugin/iso19139.ca.HNAP/schema.xsd#L7

https://github.com/metadata101/iso19139.ca.HNAP/blob/43efe958be6b8eb18acec2372e945056037b18e2/src/main/plugin/iso19139.ca.HNAP/set-thumbnail.xsl#L154

**Comment by ianwallen** [comment]
@jodygarnett, @bo-lu, @josegar74 
I noticed that there are still some links to geconnections in the metadata however the link seems to be invalid.  Is this a url that was missed during the change to https://schemas.metadata.geo.ca?

**Comment by bo-lu** [comment]
Hi Ian,

I think the geconnections is an old typo and predates everyone who is still around. It should have been referring to geoconnections, which is part of our Canadian Geospatial Data Infrastructure (CGDI) division. At some point, it appears we lost the domain (?). It seems like even with the reference to geconnections, it wasn't blocking validation. Would it be better to remove the reference or to update it?

Bo

**Comment by ianwallen** [comment]
I don't think we can remove it.  So I think updating is the only option.  It should be straight forward if we agree that we can use  https://schemas.metadata.geo.ca/2009/napm

**Comment by bo-lu** [comment]
I have no issues as long as it has been tested and is working properly. Can we wait for Jody's feedback before proceeding?

**Comment by jodygarnett** [comment]
I am out of quick feedback cycle - is there a specific example?

the html files have been edited and are easy to change…

**Comment by ianwallen** [comment]
@jodygarnett 
I have provided links in the description to sample file that reference http://www.geconnections.org

**Comment by jodygarnett** [comment]
Yes if a link was missed we should fix, but I think your example is a namespace?

The namespace xmlns:napm="http://www.geconnections.org/nap/napMetadataTools/napXsd/napm" is for geo connections but that is just a namespace. 

This namespace should remain unchanged. 

The documents we publish provide a location of an xsd that defined this namespace. The definition for this namespace can be internal to the hnap plugin, or for xml parsers which have downloaded a record they look at the top of the file to determine what this namespace is, and where the definition can be downloaded from.

**Comment by jodygarnett** [comment]
So “geoconnections” namespace is fine. 

The definition of this namespace has changed from “geogratis” (outdated) to “ schemas.metadata.geo.ca”

**Comment by ianwallen** [comment]
I know that http://www.geconnections.org/nap/napMetadataTools/napXsd/napm is just a namespace id and it will not break anything however don't we want these namespaces to point to correct urls?

[geoconnections is an invalid url ](http://www.geconnections.org/nap/napMetadataTools/napXsd/napm) 

http://www.geconnections.org also does not exists.

And when I look at the url it seems like it is trying to point to napm xsd which would be here
[here](https://schemas.metadata.geo.ca/2009/napm)

So to me this seems like an old url that should have been changed to geogratis a long time ago and it was missed.

**Comment by jodygarnett** [comment]
My understanding is that the geoconnections.org is just a namespace and is
not intended to be a website.

I also should very much not be changed (unless we change the hnap
standard).

If FGP wished to make a new release of hnap to change the namespaxe, with a
new version number it could be done? We should ask someone more experienced
then me if this is wise.

**Comment by jodygarnett** [comment]
@ianwallen can we we change the title to say *geoconnections URI seems invalid* to clarify the concern being raised?

**Comment by ianwallen** [comment]
@jodygarnett 
> can we we change the title to say geoconnections URI seems invalid to clarify the concern being raised?

Sorry I don't understand what you are asking.  The title already seems to be what you are asking?

I changed it to _Issue with reference to namespace geconnections_ - Not sure if that makes it better?

> If FGP wished to make a new release of hnap to change the namespaxe, with a
> new version number it could be done? We should ask someone more experienced
> then me if this is wise. 

I was not aware that https://schemas.metadata.geo.ca/2009/napm/napm.xsd had references to geconnections - thank you for pointing that out.

https://schemas.metadata.geo.ca/2009/napm/napm.xsd has the following:

`<xs:schema targetNamespace="http://www.geconnections.org/nap/napMetadataTools/napXsd/napm"`

which it out of scope of this Repository.

You are suggesting that in order to fix the issue, FGP would need to release a new version of HNAP with all the fixes in https://schemas.metadata.geo.ca/2009/napm first and then we could apply those changes to this repo.

That makes sense to me now that I see the reference in these files.  
I'm guessing that making a new HNAP version is not going to happen anytime soon so would you recommend closing this issue or keeping it open as a known issue?  Maybe we can keep it open for a little bit to see if there are any other comments.

**Comment by jodygarnett** [comment]
> Sorry I don't understand what you are asking. The title already seems to be what you are asking?

The feedback was the difference between URI (name) and URL (reference). 

We want the name to say geoconnections as it does now. That is what the hnap standard says and it is correct.  Changing the name would change the meaning. 

We want the reference to say the new physical location where definition can be retrieved from. Changing this reference does not change the meaning.

**Comment by jodygarnett** [comment]
We do not want the namespace to point to correct URLs. They are not URLs. 

We only want these to match the name that is in the hnap standard.

aside: I do not really know why XML standards are so complicated in this manner.

**Comment by jodygarnett** [comment]
Closing this as not planned, as it is subject for the hnap specification to revise.
