### ISSUE TITLE
Link incorrect for license in full view.

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#360]
When going to the advanced view to view a metadata record that has a license with the following text

Open Government Licence - Canada (http://open.canada.ca/en/open-government-licence-canada)
i.e. 

![image](https://github.com/metadata101/iso19139.ca.HNAP/assets/1868233/66c573f9-858b-4c2a-8cac-84d106b0521a)

It will display the following in the full view page.

![image](https://github.com/metadata101/iso19139.ca.HNAP/assets/1868233/00d2a6db-f392-4c7c-9b0f-bf73af2bec4b)

Clicking on the link will fail because it will attempt to go to "http://open.canada.ca/en/open-government-licence-canada)" with the ")" at the end of the url and the url will fail.

To reproduce
- create HNAP metadata record with standard license.
- View record in "full view" mode

**Comment by jodygarnett** [comment]
The text looks to be provided by https://github.com/metadata101/iso19139.ca.HNAP/blob/3.12.x/src/main/plugin/iso19139.ca.HNAP/inflate-metadata.xsl

```
                <xsl:choose>
                  <xsl:when test="$altLang = 'fra'">Open Government Licence - Canada (http://open.canada.ca/en/open-government-licence-canada)</xsl:when>
                  <xsl:otherwise>Licence du gouvernement ouvert - Canada (http://ouvert.canada.ca/fr/licence-du-gouvernement-ouvert-canada)</xsl:otherwise>
                </xsl:choose>
```

And whatever code recognizes http URLs is including the trailing `)` producing a broken link.

**Comment by josegar74** [comment]
The related code that needs to be reviewed is:

https://github.com/geonetwork/core-geonetwork/blob/4806aff89f193fd7c2a2c2bdb69fc4895c9299e1/schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl#L1133-L1143

**Comment by ianwallen** [comment]
@josegar74 
If I take a sample record and set the resource constraints to text with a url.  I see the following on the basic view (which seem correct)

![image](https://github.com/metadata101/iso19139.ca.HNAP/assets/1868233/96f87f7d-d35c-4e28-a2eb-61ea12d48fda)

But in the Full view I see the following (which is not correct)

![image](https://github.com/metadata101/iso19139.ca.HNAP/assets/1868233/10708d9c-f378-4483-8ddb-dac17571faf0)

So it seems like the basic view is using the regex that you highlighed but in the "full view", it seems to be using a different method to set the url.  And that seems to have a bug.

**Comment by jodygarnett** [comment]
The quick fix would be to add spaces around the URL: ``Open Government Licence - Canada ( http://open.canada.ca/en/open-government-licence-canada )``

**Comment by ianwallen** [comment]
I don't think it is that quick of a fix.
1 - submit a PR to HNAP to modify the template (optional)
2 - update our templates
3 - search and replace all existing occurrences in the metadata
4 - republish some records.
And we would have to hope that nobody decides to update add another licence with a link in it.

This is currently on a licence link - I don't suspect that this is an emergency that would warrant this kind of change as I doubt it is the top link that people are trying to link to. 

I would prefer to identify the root cause of the issue.

Thank you for the suggestion.

**Comment by ianwallen** [comment]
@josegar74 
The bug seems to be with this code

https://github.com/geonetwork/core-geonetwork/blob/66a8ca819192eed8754ce77697f8847e7a9d9d86/web/src/main/webapp/xslt/common/utility-tpl.xsl#L126-L141

I think it should be modified to use a similar regular expression to the code you pointed to.
Note that this code does not get applied to <gco:CharacterString> which I believe is why it was not the source of this bug.

https://github.com/geonetwork/core-geonetwork/blob/4806aff89f193fd7c2a2c2bdb69fc4895c9299e1/schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl#L1123-L1152
