### ISSUE TITLE
Overview not shown in PDF export

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#366]
This issue is based on the following issue.
https://github.com/geonetwork/core-geonetwork/issues/7540

When I attempt to export a public record as PDF - I only see the text in the overview instead of the images.

![image](https://github.com/metadata101/iso19139.ca.HNAP/assets/1868233/25039748-e543-4491-bf70-a65c5aa3815a)

**Comment by wangf1122** [comment]
The pull request https://github.com/geonetwork/core-geonetwork/issues/7540 seems fixed local file store. But not in cmis. There is some null pointer exception which the design of the code wasn't expecting the ServiceContext at all. I already have the solution on my local 3.12 version but I will continue look for 4.0 fix. Then make a secondary pull request to fix the cmis store interface

**Comment by wangf1122** [comment]
Issue is fixed and confirmed by our tester. The issue can be closed
