### ISSUE TITLE
Thesaurus titles are not translated in geonetwork 4.2 default view

### ISSUE THREAD

**Issue by tylerjmchugh** [metadata101/iso19139.ca.HNAP#384]
In the geonetwork 4.2 record "default view", the keywords thesaurus titles only show in the main language of the record regardless of the UI language.

Example scenario:

- Add a new record with a main language of English and alternate language of French
- Add some keywords from a thesaurus to the record (Ex. Government of Canada Core Subject Thesaurus)
- Open the record in the default view with the UI language set to French
![image](https://github.com/metadata101/iso19139.ca.HNAP/assets/163562062/b2f4cb98-711c-44e9-9288-398d7b235a2a)
- Under Technical Information / Informations techniques the thesaurus title appears in English
![image](https://github.com/metadata101/iso19139.ca.HNAP/assets/163562062/cf6b9e2e-a32d-4084-b2ea-2aa3f713c29e)

**Comment by tylerjmchugh** [comment]
This seems to be caused by the index using only gco:CharacterString without gmd:LocalisedCharacterString.

https://github.com/metadata101/iso19139.ca.HNAP/blob/133229ef1bf15b1a814af03462b09c65f2493ef0/src/main/plugin/iso19139.ca.HNAP/index-fields/index.xsl#L433-L436

I suspect that something similar to what is being done with the keyword values should also be done with the thesaurus title.

https://github.com/metadata101/iso19139.ca.HNAP/blob/133229ef1bf15b1a814af03462b09c65f2493ef0/src/main/plugin/iso19139.ca.HNAP/index-fields/index.xsl#L474-L477

But this seems like it would also require core-geonetwork changes as well to display the correct value. Is there a better solution without core changes?

**Comment by josegar74** [comment]
A solution, not the most elegant, but that doesn't require code changes, is to add in`Languages & translations`

https://SERVER/geonetwork/srv/eng/admin.console#/settings/languages

A translation with the key `Government of Canada Core Subject Thesaurus`, with these translations:

- English: `Government of Canada Core Subject Thesaurus`
- French: `Thésaurus des sujets de base du gouvernement du Canada`
