### ISSUE TITLE
Unit of Measurement attribute (uom) in gco:distance 

### ISSUE THREAD

**Issue by wangf1122** [metadata101/iso19139.ca.HNAP#395]
The NHAP metadata has such enrichment logic to append http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/uom/gmxUom.xml# as part of the attribute

https://github.com/metadata101/iso19139.ca.HNAP/blob/3f7ed80b30eef0e4ca4f0011f352a60b2e6987de/src/main/plugin/iso19139.ca.HNAP/update-fixed-info.xsl#L916-L922

There are two issues.

1) The xslt will append the url indefinitely. This can be easily fixed by checking if the url is already part of it

```
  <xsl:template  match="gco:Distance">
    <xsl:element name="gco:{local-name()}">
      <xsl:apply-templates select="@*"/>
      <xsl:choose>
        <xsl:when test="not(starts-with(@uom, 'http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/uom/gmxUom.xml#'))">
          <xsl:attribute name="uom">http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/uom/gmxUom.xml#<xsl:value-of select="@uom"/></xsl:attribute>
        </xsl:when>
        <xsl:otherwise>
          <xsl:attribute name="uom"><xsl:value-of select="@uom"/></xsl:attribute>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:apply-templates select="node()"/>
    </xsl:element>
  </xsl:template>
``` 

2) However issue 1 is not a big concern. But the question is **why such url needs to be added?**. Here is some sample metadata of without such url
![image](https://github.com/user-attachments/assets/b1bf2e60-71c2-4801-b7c9-3c60ab5c4584)

(https://apps.titellus.net/geonetwork/srv/eng/catalog.search#/metadata/77b14f4e-ca84-4786-9bb8-7e59b143fcb7)

But HNAP metadata behave like:
![image](https://github.com/user-attachments/assets/452fa18e-a4bc-46ca-b425-7bd3f7bb7ff3)

So if there is no real benefit of adding such url, we can proceed to remove it and keep it consistent with ISO13139?

**Comment by fxprunayre** [comment]
Not answering to your question, but indeed using only symbol for units can make more sense than URLs. At Ifremer, we recently worked on https://github.com/geonetwork/core-geonetwork/pull/8245 to facilitate encoding of units.

**Comment by wangf1122** [comment]
> Not answering to your question, but indeed using only symbol for units can make more sense than URLs. At Ifremer, we recently worked on [geonetwork/core-geonetwork#8245](https://github.com/geonetwork/core-geonetwork/pull/8245) to facilitate encoding of units.

Thanks for the input. I have prepared a pull request just in case if we are sure this is the way to go.

**Comment by josegar74** [comment]
@wangf1122 recently was added this pull request also: https://github.com/geonetwork/core-geonetwork/pull/8085 for the full view

I don't have very clear if the URL part is mandatory or not.

**Comment by wangf1122** [comment]
@josegar74 

I did some test by mock that url into the metadata and it seems working. But I can't make it work from my local host nor our dev environment. Do you know if there is any configuration to enable the formatter triggering?

Edited: I think i found the issue. The parent schema was indexed with special url parsing logic https://github.com/geonetwork/core-geonetwork/blob/22a87f68d2ec74ddbed86a83e0208fc2a8ce262d/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl#L701-L703

where HNAP has no such logic.
https://github.com/metadata101/iso19139.ca.HNAP/blob/3f7ed80b30eef0e4ca4f0011f352a60b2e6987de/src/main/plugin/iso19139.ca.HNAP/index-fields/index.xsl#L576


I will make a pull request shortly to fix the repeated url appending and default view from 

http://localhost:8080/catalogue/srv/eng/catalog.search#/metadata/6b9fa6fa-2913-4bfd-90ce-c73cef803a4a

which it obtained such information from the search engine itself.

**Comment by wangf1122** [comment]
@josegar74 @ianwallen 

I have created an updated PR to fix the issue. Please review https://github.com/metadata101/iso19139.ca.HNAP/pull/397
