### ISSUE TITLE
Rename non EC* thesaurus files to GC* 

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#53]
I believe we should rename the none ECCC specific thesaurus files to GC. 

i.e. I don't believe the `EC_States.rdf` is specific to ECCC and can probably be applied to all government departments so it may be better to have it renamed to `GC_States.rdf`.  

As I don't know all the uses for the thesaurus, I believe this should be an ECCC task.

**Comment by jodygarnett** [comment]
Is it useful to include all the remaining EC* thesaurus in the schema plugin, or should we isolate into a profile (as per https://github.com/metadata101/iso19139.ca.HNAP/issues/45 )

**Comment by ianwallen** [comment]
I don't have any issues/objections  if EC* remains in HNAP for now and maybe moved later as per #45. Just trying to clarify the current ones so that we know which one are GC and which ones are EC.

**Comment by jodygarnett** [comment]
@geothorne I believe you are looking at simplifying `rdf` files, can we look at this request at the same time.

**Comment by geothorne** [comment]
@davidblasby please help **Rename** the following RDF's:

**Organizational Prefix's:**
_GC -> Government of Canada_
_ISO -> iso.org_
_NE -> Natural Earth - www.naturalearthdata.com_
_EC -> Environment and Climate Change Canada (Environment Canada)_

**Suffix Acronyms:**
_PAA -> Program Alignment Architecture_
- [x] 1. EC_Core_Subject -> GC_Core_Subject
- [ ] 2. EC_GC_Security_Classification -> GC_Security_Level
- [x] 3. EC_Geographic_Scope -> GC_Geographic_Scope
- [x] 4. EC_Government_Titles -> GC_Departments 
       _(I believe this file is managed by Federal Geospatial Platform (FGP) for their Catalogue)_
- [x] 5. EC_ISO_Countries -> ISO_Countries
- [ ] 6. EC_Program -> EC_Program_PAA
- [x] 7. EC_WAF -> EC_Functions
- [ ] 8. regions -> NE_Global_Regions
- [x] 9. EC_States -> GC_State_Province 
- [x] 10. EC_Resource_Formats  -> GC_Resource_Format

Note: The following rdf's do not change name
11. EC_Directorate
12. EC_Branch

**Comment by davidblasby** [comment]
The following are unchanged;

EC_Content_Scope.rdf
EC_Data_Usage_Scope.rdf
EC_Information_Category.rdf
EC_Org_Names
EC_Resource_ContentTypes.rdf

The thesauri are located here;
https://github.com/metadata101/iso19139.ca.HNAP/tree/3.10.x/src/main/config/codelist/local/thesauri/place
and
https://github.com/metadata101/iso19139.ca.HNAP/tree/3.10.x/src/main/config/codelist/local/thesauri/theme

**Comment by davidblasby** [comment]
The following are NOT part of the metadata101 HNAP - likely uploaded to the running system;

EC_GC_Security_Classification
EC_Program 

EC_Directorate
EC_Branch

Nothing to change in metadata101/hnap.  If you want, add a ticket with those .rdf files and I will add them to metadata101/hnap

**Comment by davidblasby** [comment]
Regarding regions.rdf

This is part of CORE GeoNetwork - https://github.com/geonetwork/core-geonetwork/blob/master/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/place/regions.rdf

Its not something I can just change.

However, I can add add a copy of the regions.rdf and name it as "NE_Global_Regions.rdf".  Is the link, above, the correct content?

**Comment by davidblasby** [comment]
@geothorne  - please review comments, above.  I'll commit the changes in a little bit - I need to check to see if they are referenced anywhere (and I'll likely change the titles in the same PR).

NOTE - old metadata records will be referencing these files and should be updated (especially with the title changes in another ticket).

**Comment by davidblasby** [comment]
https://github.com/metadata101/iso19139.ca.HNAP/pull/75

**Comment by geothorne** [comment]
#74 - regions.rdf should stay in geonetwork-core repo not duplicates
