### ISSUE TITLE
Sample metadata records don't support add to map

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#55]
I the sample "Harbour Porpoise Presence, Maritimes Region" is loaded. Then going to the view the sample record and attempting to "add to map" will produced the following error.

Biota002_MarineMammals_HarbourPorpoise_PH_SJ_Presence
The WMS getCapabilities request failed, Failed to parse GetCapabilities operation response. Try again later or contact service provider.

![image](https://user-images.githubusercontent.com/1868233/84702911-bd261480-af2d-11ea-8011-5bddb0ae0fce.png)

I believe a lot of the published Open Data records also have similar issues. So I don't believe it is just a matter of fixing the sample records.  May need a goenetwork core modification?

Any suggestions?

**Comment by geothorne** [comment]
@ianwallen is this still an issue, can it be closed? Sorry for the house cleaning

**Comment by ianwallen** [comment]
Issue is fixed in the 3.10.4 release of GN with the following pull request.
https://github.com/geonetwork/core-geonetwork/pull/4784

So yes we can close the issue.
