### ISSUE TITLE
GC Core and other Thesaurus - not validating in editor

### ISSUE THREAD

**Issue by geothorne** [metadata101/iso19139.ca.HNAP#63]
![GC-Core-Validation-ISSUE](https://user-images.githubusercontent.com/47672199/87073805-f3cd1300-c1eb-11ea-9e3f-878389b2c6ee.PNG)

https://iso19139echnap.geocat.live/geonetwork/srv/eng/catalog.search#/metadata/2aa3a4ff-7c4c-44d0-a4e2-9ab1a1df0d56

[2aa3a4ff-7c4c-44d0-a4e2-9ab1a1df0d56.zip](https://github.com/metadata101/iso19139.ca.HNAP/files/4898943/2aa3a4ff-7c4c-44d0-a4e2-9ab1a1df0d56.zip)

I imported this attached mef published ECCC I am unable to completely validate in the editor.  see image. you can test with the mef attached.

**Comment by josegar74** [comment]
With https://github.com/metadata101/iso19139.ca.HNAP/pull/60 and the metadata added in #64 works fine, but there's some validation issue with `gmd:administrativeArea `, the original metadata has this value as non-multilingual, but it's expected to be multilingual.

The editor seem adds the element `gmd:PT_FreeText`, but with empty content causing the validation issue: 

```
<gmd:administrativeArea xsi:type="gmd:PT_FreeText_PropertyType">
  <gco:CharacterString>QC</gco:CharacterString>
  <gmd:PT_FreeText/>
</gmd:administrativeArea>
```

If the user fills the value in the UI it fixes the issue, but I think it's caused as the value is retrieved from a vocaulary and the value `QC` is not defined (it's defined `Quebec`). Maybe we need to add some conversion process in the metadata to translate this codes?

**Comment by geothorne** [comment]
In my mind if we were to fix the `QC` to `Quebec`. I am think there is another issue here and that the RDF that holds provinces does not have the provincial code using the '<skos:notation>' element.

Allowing us to convert between PreLabel and Notations terms in the editor.... does GeoNetwork have this use case for managing thesaurus? 

This is instead of creating a hard code values within a custom translations. If that makes sense to you and you also recommend?

**Comment by davidblasby** [comment]
Hi,

I've tried to reproduce this issue - but its mostly validating.  The only validation error is unrelated to the thesaurus;

![image](https://user-images.githubusercontent.com/48937730/88710339-5f0f5400-d0cb-11ea-8996-fca9a3c792fd.png)

There's been a lot of recent work on Thesaurus, so the reversion out on LIVE might be old...

Perhaps we can close this issue and re-open another one WRT QC/Quebec?

**Comment by geothorne** [comment]
@davidblasby I agree with your assessment. Will review again and if required create new Issue
