### ISSUE TITLE
Editor French and English Tool help tips

### ISSUE THREAD

**Issue by geothorne** [metadata101/iso19139.ca.HNAP#67]
I would like to understand the process needed to review and edit French and English update help tool. Where do are tips managed within the repository?

**Comment by josegar74** [comment]
Schema elements labels and tooltips are stored in:

- English: https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/eng/labels.xml

- French: https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/loc/fre/labels.xml

In the following file are documented the elements from previous files:

https://github.com/geonetwork/core-geonetwork/blob/master/schemas/schema-labels.xsd

The tooltips are stored in `description` and `help` elements.

**Comment by jodygarnett** [comment]
Closing this as answered.
