### ISSUE TITLE
iso19139.ca.HNAP release

### ISSUE THREAD

**Issue by jodygarnett** [metadata101/iso19139.ca.HNAP#94]
A couple things for a release, based on core-genetwork example:

* [x] commit changing from `3.10.4-SNAPSHOT` to `3.10.4`
* [x] tag the above commit
* [x] mark the tag as a release in GitHub, fill in some release notes
* [x] attach `jar` and `zip` to release
* [x] commit changing from `3.10.4` to `3.10.5-SNAPSHOT` to match the `3.10.x` branch.
* [x] Create a `3.10.4` milestone to collect a list of closed issues and pull requests

Known issues:

* Because the `3.10.4` branch uses schemas `3.7` as a parent there is no great way to enforce we are getting the correct transitive dependencies from core-geonetwork. As a workaround please be sure to build the core-geonetwork `3.10.4` tag locally. To avoid conflict all the transitive dependencies from core-geonetwork have been marked as scope provided.

**Comment by jodygarnett** [comment]
Created a milestone to easily manage issues and PRs for release notes.

**Comment by ianwallen** [comment]
@jodygarnett - I see that you created the 3.10.4 milestone but I also see that it is still open?  Should it remain open?
Should there be a new 3.10.5 milestone so that we apply new changes to this milestone?

**Comment by jodygarnett** [comment]
I should of closed it, sorry I am learning the system.
